# Generated by Django 4.0.3 on 2022-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('duracion', models.CharField(max_length=200)),

            ],
        ),
    ]
